name: CI

on:
  push:
    branches:
      - ZbayLite

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/ZbayLite
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: install rustfmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-apple-darwin
      - name: install dependencies
        run: npm install
      - name: install neon
        run: npm install --global neon-cli
      - name: build  binary
        run: npm run neon
      - name: build on Mac
        run: npm run build:prod
      - name: install electron builder
        run: npm install -g electron-builder@22.3.2
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: electron-builder -p always --mac
